### PR TITLE
Fixed Grammar

### PR DESCRIPTION
**Pull request by LauSnchz**
- Made grammar correction

### CODE REVIEW

**Review by KoolieAid — COMMENTED** [review]
any other grammar errors?

**Comment by LauSnchz** [comment]
> any other grammar errors?

@daleabellaa saw the grammar issues and I corrected them. So far so good

**Comment by KoolieAid** [comment]
> > any other grammar errors?
> 
> @daleabellaa saw the grammar issues and I corrected them. So far so good

can u double check the files

**Comment by LauSnchz** [comment]
Okay loos good

**Review by daleabellaa — COMMENTED** [review]
for the Pagong request: change ng to nang. this should be "gumagapang **nang** mabagal." the other 2 changes are good.
image

**Review by KoolieAid — APPROVED** [review]

**Pull request merged**
