### PR TITLE
Updated credits

### PR DESCRIPTION
**Pull request by daleabellaa**
Included roles, capstn adviser, music and sound fx source & partner / client in credits

### CODE REVIEW

**Review by AlexanderGregorSanchez — APPROVED** [review]

**Review by KoolieAid — CHANGES_REQUESTED** [review]
Did you delete the old version or we reusing it next time ~~as if there's a next time~~

**Comment by daleabellaa** [comment]
> Did you delete the old version or we reusing it next time ~~as if there's a next time~~

I just replaced the image, the old one is still in Art Assets > CREDITS Folder, for reference. And no I dont think we're going to reuse it.

**Comment by KoolieAid** [comment]
> > Did you delete the old version or we reusing it next time ~~as if there's a next time~~
> 
> I just replaced the image, the old one is still in Art Assets > CREDITS Folder, for reference. And no I dont think we're going to reuse it (edit: might as well delete doesnt matter)

Yea just delete it, then commit

**Comment by daleabellaa** [comment]
just deleted old credits image. done with "fix/update-credits-image" branch.

**Review by KoolieAid — APPROVED** [review]

**Pull request merged**
